spring:
  # nacos 配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 网关配置
    gateway:
      routes:
        - id: zoj-backend-user-service
          uri: lb://zoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: zoj-backend-question-service
          uri: lb://zoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: zoj-backend-judge-service
          uri: lb://zoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: zoj-backend-gateway
  main:
    web-application-type: reactive
# 端口
server:
  port: 8804
# 接口文档
knife4j:
  gateway:
    # 是否开启
    enabled: true
    strategy: discover
    discover:
      # 开启
      enabled: true
      version: swagger2